name: pub_updater
description: A Dart package which enables checking whether a package is up to date.
version: 0.5.0
repository: https://github.com/VeryGoodOpenSource/pub_updater
issue_tracker: https://github.com/VeryGoodOpenSource/pub_updater/issues
topics: [cli, pub, version]

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0
  process: ^5.0.2
  pub_semver: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ">=7.0.0 <10.0.0"
