name: pub_updater
description: A Dart package which enables checking whether a package is up to date.
version: 0.5.0
repository: https://github.com/VeryGoodOpenSource/pub_updater
issue_tracker: https://github.com/VeryGoodOpenSource/pub_updater/issues
topics: [cli, pub, version]

environment:
  sdk: ^3.9.0

dependencies:
  http: ^1.5.0
  json_annotation: ^4.9.0
  process: ^5.0.5
  pub_semver: ^2.2.0

dev_dependencies:
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^10.0.0
